steps:
# Install
  - name: 'gcr.io/cloud-architect-certifications/npm'
    args: ['install']
# Build
  - name: 'gcr.io/cloud-architect-certifications/npm'
    args: ['run', 'build']
# Deploy
  - name: 'gcr.io/cloud-architect-certifications/gcloud'
    args: ['app', 'deploy']
