steps:
#Info
  - name: gcr.io/cloud-builders/git
    args: ["fetch", "--unshallow"]
  - name: gcr.io/cloud-builders/git
    entrypoint: /bin/bash
    args: ["-c", "echo ${_MAJOR}.${_MINOR}.${_PATCH}.$(git rev-list --count ${BRANCH_NAME}) > IMAGE_TAG"]
# Install
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
# Replaces
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'replaceEnvs']
# Build
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
# Deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
